# Generated by Django 3.2.20 on 2023-08-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230824_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(default=1, max_length=25, verbose_name='Category Path'),
            preserve_default=False,
        ),
    ]
