# Generated by Django 3.2.20 on 2023-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, editable=False, max_length=25, verbose_name='Category Path'),
        ),
    ]
